import ExcelJS from 'exceljs';
import { Expense } from './supabase';

export const generateAccountingExcel = async (expenses: Expense[], orgName: string, dateRange: string) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'ExpenseLens';
  workbook.lastModifiedBy = 'ExpenseLens';
  workbook.created = new Date();
  workbook.modified = new Date();

  // 1. Transactions Sheet
  const sheet = workbook.addWorksheet('Expenses', {
    views: [{ state: 'frozen', xSplit: 0, ySplit: 1 }] // Freeze header row
  });

  // Define Columns
  sheet.columns = [
    { header: 'Date', key: 'date', width: 15 },
    { header: 'Merchant', key: 'merchant', width: 25 },
    { header: 'Category', key: 'category', width: 20 },
    { header: 'Description', key: 'description', width: 35 },
    { header: 'Amount (IDR)', key: 'amount', width: 20 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Receipt URL', key: 'receipt', width: 40 },
    { header: 'Expense ID', key: 'id', width: 36 },
  ];

  // Styiling Header Row
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FFFFFF' }, size: 12 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: '022c22' } // Primary Dark Green
  };
  headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
  headerRow.height = 30;

  // Add Data
  let totalAmount = 0;

  expenses.forEach(exp => {
    totalAmount += exp.amount;

    const row = sheet.addRow({
      date: new Date(exp.date),
      merchant: exp.merchant_name,
      category: exp.category,
      description: exp.description || '-',
      amount: exp.amount,
      status: exp.status,
      receipt: exp.image_url ? { text: 'View Receipt', hyperlink: exp.image_url } : 'No Receipt',
      id: exp.id
    });

    // Row Styling
    row.getCell('amount').numFmt = '#,##0.00'; // Currency Format
    row.getCell('date').numFmt = 'dd/mmm/yyyy';
    row.alignment = { vertical: 'middle', horizontal: 'left' };

    // Status Badge Logic (Color text)
    if (exp.status === 'VERIFIED') {
        row.getCell('status').font = { color: { argb: '006400' }, bold: true }; // Dark Green
    } else {
        row.getCell('status').font = { color: { argb: '808080' }, italic: true }; // Grey
    }

    // Receipt Link Style
    if (exp.image_url) {
        row.getCell('receipt').font = { color: { argb: '0000FF' }, underline: true };
    }
  });

  // Add Summary / Totals Row
  const summaryRowNumber = expenses.length + 3;
  const summaryRow = sheet.getRow(summaryRowNumber);
  summaryRow.getCell('description').value = 'TOTAL';
  summaryRow.getCell('description').font = { bold: true };
  summaryRow.getCell('description').alignment = { horizontal: 'right' };

  summaryRow.getCell('amount').value = totalAmount;
  summaryRow.getCell('amount').font = { bold: true };
  summaryRow.getCell('amount').numFmt = 'Rp #,##0.00';
  summaryRow.getCell('amount').fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'bfd852' } // Accent Color
  };

  // 2. Metadata / Info Sheet (Professional Touch)
  const metaSheet = workbook.addWorksheet('Report Info');
  metaSheet.getColumn(1).width = 20;
  metaSheet.getColumn(2).width = 40;

  metaSheet.addRow(['Generated By', 'ExpenseLens Accounting System']);
  metaSheet.addRow(['Organization', orgName]);
  metaSheet.addRow(['Date Range', dateRange]);
  metaSheet.addRow(['Export Date', new Date().toLocaleString()]);
  metaSheet.addRow(['Total Records', expenses.length]);

  // Generate File
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });

  return blob;
};
